### ISSUE TITLE
--mangoapp parameter doesn't use system's mangohud.conf

### ISSUE THREAD

**Issue by Virkkunen** [ValveSoftware/gamescope#1402]
I'm running endeavourOS `Linux endeavour 6.9.7-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:27 +0000 x86_64 GNU/Linux`, and it's a fresh install of the `mangohud` and `gamescope` packages from Arch's repositories.
  
I've created a `~/.config/MangoHud/mangohud.conf` file with the following contents:
  
```toml
legacy_layout=false

horizontal
background_alpha=0.0
round_corners=0
background_alpha=0.0
background_color=000000

font_size=18
text_color=CDD6F4
position=top-left
toggle_hud=Shift_R+F12
pci_dev=0:08:00.0
table_columns=3
fps
fps_limit_method=late
gpu_text=GPU
gpu_stats
gpu_load_change
gpu_load_value=50,90
gpu_load_color=FFFFFF,FFAA7F,CC0000
gpu_temp
gpu_power
vram
vram_color=B4BEFE
cpu_text=CPU
cpu_stats
core_bars
cpu_load_change
cpu_load_value=50,90
cpu_load_color=FFFFFF,FFAA7F,CC0000
cpu_temp
ram
ram_color=89B4FA
toggle_fps_limit=Shift_L+F1

fps_limit=0
resolution
hdr
refresh_rate
gamemode
fps_color_change
fps_color=B22222,FDFD09,39F900
fps_value=60,82
vsync=0
gl_vsync=-1

output_folder=/home/vrkknn
log_duration=30
autostart_log=0
log_interval=100
toggle_logging=Shift_L+F2
```
  
If I run gamescope and use `mangohud` as part of the launch parameters (be it on Steam or from terminal), my mangohud configuration is properly loaded. My launch parameters, and a screenshot of the hud:
  
`gamescope -W 3840 -H 2160 -r 165 --hdr-enabled --hdr-itm-enable --hdr-itm-sdr-nits 300 --hdr-sdr-content-nits 300 -f -e -- mangohud gamemoderun %command%`
  
![20240630_123741](https://github.com/ValveSoftware/gamescope/assets/9111925/9795040d-d493-4538-aa2c-9bc241cf17c9)
  
However, if I change `mangohud` to `--mangoapp`, as it is the preferred way of running it, it defaults to an empty configuration:
  
`gamescope -W 3840 -H 2160 -r 165 --hdr-enabled --hdr-itm-enable --hdr-itm-sdr-nits 300 --hdr-sdr-content-nits 300 -f -e --mangoapp -- gamemoderun %command%`  
  
![20240630_123854](https://github.com/ValveSoftware/gamescope/assets/9111925/503c8fd3-b28b-47de-b84e-6e31d5c5f86e)
  
I've set `MANGOHUD_CONFIGFILE=/home/vrkknn/.config/MangoHud/mangohud.conf` on my `/etc/environment` to no avail. I also symlinked `/home/vrkknn/.steam/steam/config/mangohud.conf` to `/home/vrkknn/.config/MangoHud/mangohud.conf` and no changes were made. 
  
What's going on here?
