### ISSUE TITLE
Gamescope 3.16.3 doesn't work with KDE Plasma 6.3.4

### ISSUE THREAD

**Issue by btegs** [ValveSoftware/gamescope#1798]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [x] The issue occurs on upstream gamescope without any modifications

### Current Behavior

Install Gamescope via Flatpak to use with the Flatpak version of Steam. Both are using the 24.08 runtimes:

```
Steam                           com.valvesoftware.Steam                                             1.0.0.81                 stable      user
gamescope                 org.freedesktop.Platform.VulkanLayer.gamescope  3.16.3                    24.08   user
```

When changing the Launch Options for a Steam game using 3.16.3 under a Wayland session with KDE Plasma 6.3.4, the Wayland window will run but be stuck in the KDE Task Manager. Previous version (3.16.2) ran fine. Downgrading Gamescope fixed the issue.

### Steps To Reproduce

1. Install Steam in flatpak: `com.valvesoftware.Steam`
2. Install gamescope in flatpak: `org.freedesktop.Platform.VulkanLayer.gamescope/x86_64/24.08`
3. Change launch option for a Steam game. This is Cyberpunk 2077: 
```
gamescope --adaptive-sync --force-grab-cursor --hdr-enabled -W 3440 -H 1440 -r 144 -f -e -- %command% --launcher-skip --intro-skip -skipStartScreen
```

4. Game launches, but then is stuck in Task Manager
5. Force quit the game and Steam
6. Downgrade Gamescope to 3.16.2:
```
flatpak update --commit=b0e64bdc415c23261ef3deb23d849cdd2d410d3e020527d42ed85c01cce07643 org.freedesktop.Platform.VulkanLayer.gamescope/x86_64/24.08
```
7. Open Steam and Launch game
8. Game opens in fullscreen as intended

NOTE: Heroic Games Launcher uses the 23.08 Flatpak runtime and uses 3.16.2 as the latest. Games launch fine within Heroic using the 3.16.2 version of Gamescope.

### Hardware information

```markdown
- Distro: Kubuntu 25.04
- CPU: AMD Ryzen 7 5800X3D 8-Core Processor
- GPU: AMD Radeon RX 6900 XT (radeonsi, navi21, LLVM 19.1.7, DRM 3.61, 6.14.0-13-generic)
- Driver Version (System): Mesa 25.0.3-1ubuntu1 (LLVM 19.1.7)
- Driver Version (Flatpak): 4.6 (Compatibility Profile) Mesa 24.3.4 (git-769e51468b)
```

### Software information

```markdown
- Desktop environment: KDE Plasma 6.3.4
- Session type: Wayland
- Gamescope version: 3.16.3 (Flatpak)
- Gamescope launch command(s): gamescope --adaptive-sync --force-grab-cursor --hdr-enabled -W 3440 -H 1440 -r 144 -f -e -- %command% --launcher-skip --intro-skip -skipStartScreen
```

### Which gamescope backends have the issue you are reporting?

- [x] Wayland (default for nested gamescope)
- [ ] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

### Logging, screenshots, or anything else

**Get Info**

```
flatpak remote-info --log flathub org.freedesktop.Platform.VulkanLayer.gamescope/x86_64/24.08
```

```
gamescope - The micro-compositor formerly known as steamcompmgr

        ID: org.freedesktop.Platform.VulkanLayer.gamescope
       Ref: runtime/org.freedesktop.Platform.VulkanLayer.gamescope/x86_64/24.08
      Arch: x86_64
    Branch: 24.08
   Version: 3.16.3
   License: BSD-2-Clause
Collection: org.flathub.Stable
  Download: 44.1 MB
 Installed: 122.7 MB

    Commit: 051868eeb5cc3737c22ba3728b80af544162da74e19dd8bbdf2cc6b49ecbf6a4
    Parent: b0e64bdc415c23261ef3deb23d849cdd2d410d3e020527d42ed85c01cce07643
   Subject: Update gamescope 3.16.3, remove scripts patch (630a30a4)
      Date: 2025-04-02 11:50:43 +0000
   History: 

    Commit: b0e64bdc415c23261ef3deb23d849cdd2d410d3e020527d42ed85c01cce07643
   Subject: Update hwdata, gamescope, libinput, xwayland, libei and luajit modules (2196536a)
      Date: 2025-03-02 13:12:34 +0000

    Commit: 65cf0c8f188bcb4e4fc75f720a73768e6ade6502c2b87564938ea9334b367950
   Subject: seatd: Update 0.8.0.tar.gz to 0.9.1 (9a705fb6)
      Date: 2024-12-20 13:28:37 +0000

    Commit: 709c12b1664105cc455345d786759642dba08cdd4bd667b0cca51a3516344848
   Subject: cleanup modprobe.d from hwdata (#286) (7dfb3b52)
      Date: 2024-12-20 01:26:42 +0000

    Commit: a29ef699d749bf23262354fdf0da931d33fdb228c2a4bb67b25f9ce862df71f1
   Subject: Update gamescope to 3.16.1 (#285) (d7474be7)
      Date: 2024-12-18 13:39:54 +0000

    Commit: b3ce5ac9ce3ae0cbe4b701a8d32959185c5e995472a6bd6bdee73b9b8e92eb08
   Subject: Update platform to 24.08 (a3796e50)
      Date: 2024-09-09 14:19:59 +0000
```

**Force previous version**

```
flatpak update --commit=b0e64bdc415c23261ef3deb23d849cdd2d410d3e020527d42ed85c01cce07643 org.freedesktop.Platform.VulkanLayer.gamescope/x86_64/24.08
```

**Check**
```
flatpak list | grep gamescope
```

```
gamescope       org.freedesktop.Platform.VulkanLayer.gamescope  3.16.2  23.08   user
gamescope       org.freedesktop.Platform.VulkanLayer.gamescope  3.16.2  24.08   user
